import tkinter
window = tkinter.Tk()
def calculate():
    bt.delete(0,'end')
    height = ht.get()
    weight = wt.get()
    bmi = float(weight) / (float(height)*float(height))
    bmi = round(bmi,2)
    bt.insert(0,str(bmi))
window.title("BMI Calculator")
window.geometry('200x125')
hl = tkinter.Label(window, text = "Height (in Meters)")
hl.grid(column = 0, row = 0)
wl = tkinter.Label(window, text = "Weight (in Kg)")
wl.grid(column = 0, row = 1)
bl = tkinter.Label(window, text = "Your BMI")
bl.grid(column = 0, row = 2)
bt = tkinter.Button(window, text="Calculate", command = calculate)
bt.grid(column = 1 , row = 4)
ht = tkinter.Entry(window, width=10)
ht.grid(column = 1, row = 0)
wt = tkinter.Entry(window, width=10)
wt.grid(column = 1, row = 1)
bt = tkinter.Entry(window, width=10)
bt.grid(column = 1, row = 2)
window.mainloop()