from tkinter import *
root=Tk()
root.geometry("300x150")
root.configure(background="gray")
root.title("BMI Calculator")
def calculate():
    b_field.delete(0,"end")
    h1=height_field.get()
    w1=weight_field.get()
    b1=float(w1)/(float(h1)*float(h1))
    b_field.insert(0,b1)
height_field = Entry(root,width=20)
height_field.grid(column=1, row=1)
hlabel = Label(root,text="Height (in Meter)")
hlabel.grid(column=0, row=1)
weight_field = Entry(root, width=20)
weight_field.grid(column=1,row=3)
wlabel = Label(root,text="Weight (in Kg)")
wlabel.grid(column=0,row=3)
b1_button = Button(root,text="calculate",fg="black",command="calculate")
b1_button.grid(column=1,row=7)
blabel = Label(root,text="BMI")
blabel.grid(column=0,row=5)
b_field = Entry(root,width=20)
b_field.grid(column=1,row=5)
root.mainloop()